var alphabet = {
  "a" : ["Angular.js", "ASP.NET", "Apache"],
  "b" : ["Bootstrap", "Bower", "Bitbucket", "Backbone.js"],
  "c" : ["C", "C++", "CSS"],
  "d" : ["D3.js", "DynamoDB", "Docker", "Django", "DigitalOcean"],
  "e" : ["Ember.js", "Express", "Emacs"],
  "f" : ["F#", "Flask"],
  "g" : ["Go", "Git", "Grunt"],
  "h" : ["Hadoop", "Heroku", "Handlebars.js"],
  "i" : ["io.js", "IFTTT"],
  "j" : ["jQuery", "jQuery UI", "jQuery Mobile", "JSON"],
  "k" : ["Knockout"],
  "l" : ["Linux", "LESS"],
  "m" : ["Materialize", "MongoDB", "MySQL", "Modernizr", "Meteor"],
  "n" : ["Node.js", "nginx", "npm"],
  "o" : ["Objective-C", "Oracle"],
  "p" : ["PDF.js", "PHP", "Python"],
  "q" : ["QUnit.js", "Qualaroo"],
  "r" : ["React.js", "Ruby", "Ruby on Rails", "Redis"],
  "s" : ["SASS", "SQL Server", "Scala", "Stripe"],
  "t" : ["Travis CLI", "Trello"],
  "u" : ["Underscore.js", "UNIX", "Unicode"],
  "v" : ["Vim", "VirtualBox", "VisualStudio"],
  "w" : ["Windows Server", "Windows Azure", "Worpress"],
  "x" : ["XML", "Xcode"],
  "y" : ["YAML", "Yeoman"],
  "z" : ["Zendesk", "Zapier", "ZenHub"]
};
